
CREATE TABLE PUBLIC.TI18N (
	ID_I18N INT GENERATED ALWAYS AS IDENTITY (INCREMENT BY 3 START WITH 7),
	CLASS_NAME VARCHAR(150),
	I18N_DESCRIPTION VARCHAR(250),
	CONSTRAINT SYS_PK_10124 PRIMARY KEY (ID_I18N)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10124_10125 ON PUBLIC.TI18N (ID_I18N);


CREATE TABLE PUBLIC.TI18N_VALUE (
	ID_I18N_VALUE INT NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT BY 3 START WITH 7),
	ID_I18N INT NOT NULL,
	"KEY" VARCHAR(250),
	ES_ES VARCHAR(10485760),
	EN_US VARCHAR(10485760),
	GL_ES VARCHAR(10485760),
	CONSTRAINT SYS_PK_10128 PRIMARY KEY (ID_I18N_VALUE)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10128_10130 ON PUBLIC.TI18N_VALUE (ID_I18N_VALUE);

CREATE TABLE PUBLIC.TREQUEST_STATISTICS (
	ID_REQUEST_STATISTICS INT NOT NULL,
	SERVICE_NAME VARCHAR(255),
	METHOD_NAME VARCHAR(50),
	USER_NAME VARCHAR(50),
	EXECUTION_DATE DATE,
	EXECUTION_TIME INT,
	METHOD_PARAMS VARCHAR(5000),
	SERVICE_EXCEPTION VARCHAR(5000),
	CONSTRAINT SYS_PK_10112 PRIMARY KEY (ID_REQUEST_STATISTICS)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10112_10113 ON PUBLIC.TREQUEST_STATISTICS (ID_REQUEST_STATISTICS);


CREATE TABLE PUBLIC.TROLE (
	ID_ROLENAME INT NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT BY 3 START WITH 7),
	ROLENAME VARCHAR(255),
	XMLCLIENTPERMISSION VARCHAR(10485760),
	CONSTRAINT SYS_PK_10096 PRIMARY KEY (ID_ROLENAME)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10096_10097 ON PUBLIC.TROLE (ID_ROLENAME);

CREATE TABLE PUBLIC.TSERVER_PERMISSION (
	ID_SERVER_PERMISSION INT NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT BY 3 START WITH 7),
	PERMISSION_NAME VARCHAR(10485760),
	CONSTRAINT SYS_PK_10108 PRIMARY KEY (ID_SERVER_PERMISSION)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10108_10109 ON PUBLIC.TSERVER_PERMISSION (ID_SERVER_PERMISSION);



CREATE TABLE PUBLIC.TSETTING (
	ID_SETTING INT NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT BY 3 START WITH 7),
	SETTING_KEY VARCHAR(10485760),
	SETTING_VALUE VARCHAR(10485760),
	SETTING_COMMENT VARCHAR(10485760),
	CONSTRAINT SYS_PK_10116 PRIMARY KEY (ID_SETTING)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10116_10117 ON PUBLIC.TSETTING (ID_SETTING);



CREATE TABLE PUBLIC.TUSER (
	USER_ VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50),
	NAME VARCHAR(50),
	SURNAME VARCHAR(50),
	EMAIL VARCHAR(50),
	NIF VARCHAR(50),
	USERBLOCKED TIMESTAMP,
	LASTPASSWORDUPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FIRSTLOGIN BOOLEAN DEFAULT TRUE,
	CONSTRAINT SYS_PK_10092 PRIMARY KEY (USER_)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10092_10093 ON PUBLIC.TUSER (USER_);


CREATE TABLE PUBLIC.TROLE_SERVER_PERMISSION (
	ID_ROLE_SERVER_PERMISSION INT NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT BY 3 START WITH 7),
	ID_ROLENAME INT,
	ID_SERVER_PERMISSION INT,
	CONSTRAINT SYS_PK_10134 PRIMARY KEY (ID_ROLE_SERVER_PERMISSION),
	CONSTRAINT FK_TROLE_SERVER_PERMISSION FOREIGN KEY (ID_ROLENAME) REFERENCES PUBLIC.TROLE(ID_ROLENAME),
	CONSTRAINT FK_TSERVER_PERMISSION FOREIGN KEY (ID_SERVER_PERMISSION) REFERENCES PUBLIC.TSERVER_PERMISSION(ID_SERVER_PERMISSION)
);
CREATE INDEX SYS_IDX_10137 ON PUBLIC.TROLE_SERVER_PERMISSION (ID_ROLENAME);
CREATE INDEX SYS_IDX_10139 ON PUBLIC.TROLE_SERVER_PERMISSION (ID_SERVER_PERMISSION);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10134_10135 ON PUBLIC.TROLE_SERVER_PERMISSION (ID_ROLE_SERVER_PERMISSION);
CREATE TABLE PUBLIC.TUSER_PREFERENCE (
 ID_USER_PREFERENCE INT NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT BY 3 START WITH 7),
 PREFERENCE_NAME VARCHAR(150),
 USER_LOGIN VARCHAR(150),
 PREFERENCE_VALUE VARCHAR(10485760),
 CONSTRAINT SYS_PK_10120 PRIMARY KEY (ID_USER_PREFERENCE)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10120_10121 ON PUBLIC.TUSER_PREFERENCE (ID_USER_PREFERENCE);

CREATE TABLE PUBLIC.TUSER_ROLE (
	ID_USER_ROLE INT NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT BY 3 START WITH 7),
	ID_ROLENAME INT,
	USER_ VARCHAR(50),
	CONSTRAINT SYS_PK_10100 PRIMARY KEY (ID_USER_ROLE),
	CONSTRAINT FK_TROLE FOREIGN KEY (ID_ROLENAME) REFERENCES PUBLIC.TROLE(ID_ROLENAME),
	CONSTRAINT FK_TUSER FOREIGN KEY (USER_) REFERENCES PUBLIC.TUSER(USER_)
);
CREATE INDEX SYS_IDX_10103 ON PUBLIC.TUSER_ROLE (USER_);
CREATE INDEX SYS_IDX_10105 ON PUBLIC.TUSER_ROLE (ID_ROLENAME);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10100_10101 ON PUBLIC.TUSER_ROLE (ID_USER_ROLE);
